import { Brand, Option } from "effect";
import type { Artist } from "./artist";
import type { Track } from "./track";
import type { ProviderId } from "./provider-metadata";

/**
 * Wrapper around a string to represent an album id.
 */
export type AlbumId = string & Brand.Brand<"AlbumId">;
export const AlbumId = Brand.nominal<AlbumId>();

/**
 * Represents information about an album without including the tracks.
 */
export type AlbumInfo = {
  /**
   * Unique identifier for the album, either provided by a third-party (when
   * syncing against API-based services) or generated by the application. If the
   * ID is from a third-party, the first three characters of the service name
   * followed by a colon are prepended to the ID. Example: `spo:id` for an ID
   * generated by the Spotify API.
   */
  id: AlbumId;

  /**
   * Artist of the album.
   */
  artist: Artist;

  /**
   * Name of the album.
   */
  name: string;

  /**
   * Year in which the album was released.
   */
  releaseYear: Option.Option<number>;

  /**
   * Cover art of the album as a blob.
   */
  embeddedCover: Option.Option<Blob>;

  /**
   * Provider that hosts the album.
   */
  providerId: ProviderId;
};

/**
 * Represents an album in the user's library.
 */
export type Album = {
  /**
   * All tracks that are part of the album.
   */
  tracks: Track[];
} & AlbumInfo;
