import * as S from "@effect/schema/Schema";
import { GenericId } from "./common";
import { ArtistId } from "./artist";

/**
 * Wrapper around a string to represent an album id.
 */
export const AlbumId = S.Union(S.String.pipe(S.startsWith("spo:")), GenericId);
export type AlbumId = S.Schema.Type<typeof AlbumId>;

/**
 * Represents an album in the user's library.
 */
export const Album = S.Struct({
  /**
   * Unique identifier for the album, either provided by a third-party (when
   * syncing against API-based services) or generated by the application. If the
   * ID is from a third-party, the first three characters of the service name
   * followed by a colon are prepended to the ID. Example: `spo:id` for an ID
   * generated by the Spotify API.
   */
  id: AlbumId,

  /**
   * Unique identifier for the artist of the album.
   */
  artistId: ArtistId,

  /**
   * Name of the album.
   */
  name: S.String.pipe(S.nonEmpty()),

  /**
   * URL to an image of the album. This is typically the album's cover art on a
   * third-party service. If none is available, this field is omitted.
   */
  imageUrl: S.Option(S.String),
});
export type Album = S.Schema.Type<typeof Album>;
