import { Brand, Option } from "effect";
import type { Artist } from "./artist";
import type { Track } from "./track";

/**
 * Wrapper around a string to represent an album id.
 */
export type AlbumId = string & Brand.Brand<"AlbumId">;
export const AlbumId = Brand.nominal<AlbumId>();

/**
 * Represents an album in the user's library.
 */
export type Album = {
  /**
   * Unique identifier for the album, either provided by a third-party (when
   * syncing against API-based services) or generated by the application. If the
   * ID is from a third-party, the first three characters of the service name
   * followed by a colon are prepended to the ID. Example: `spo:id` for an ID
   * generated by the Spotify API.
   */
  id: AlbumId;

  /**
   * Artist of the album.
   */
  artist: Artist;

  /**
   * Name of the album.
   */
  name: string;

  /**
   * All tracks that are part of the album.
   */
  tracks: Track[];

  /**
   * URL to an image of the album. This is typically the album's cover art on a
   * third-party service. If none is available, this field is omitted.
   */
  imageUrl: Option.Option<string>;
};
